name: Gatsby Publish Site

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - run: |
        cd wozzyio; npm install; npm run deploy;
        cd ../
        find . ! -name 'Makefile' ! -name 'LICENSE' ! -name 'CHANGELOG.md' ! -name 'wozzyio' ! -name '.git' ! -name '.gitignore' ! -name 'README.md' -type d -exec rm -rf {} +
        cd wozzyio/public; cp -r * ../../
    - run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Create New Release" -a
    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.DEPLOY_TOKEN }}
        branch: ${{ github.ref }}
